source 'http://rubygems.org'

gem 'rails'

gem 'sqlite3'

gem 'sass-rails'
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platform => :ruby

gem 'uglifier'
gem 'bootstrap-wysihtml5-rails', :path => '../'
gem 'jquery-rails'
gem 'anjlab-bootstrap-rails', "~> 2.0.4.4", require: 'bootstrap-rails'
